### ISSUE TITLE
Erros em log

### ISSUE THREAD

**Issue by talissonf** [ecomclub/app-wirecard#20]
Erro em log
```
ecomplus-modules [Mon Oct 28 2019 07:26:10 GMT-0300 (Brasilia Standard Time)] 
WIRECARD_NOTIFICATION_ERR
Error: {"error":"resource not found"}
    at Request.rq [as _callback] (/var/nodejs/wirecard/routes/wirecard/notifications.js:86:16)
    at Request.self.callback (/var/nodejs/wirecard/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/var/nodejs/wirecard/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/var/nodejs/wirecard/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  ---  //  ---  
`

**Comment by talissonf** [comment]
#21
